# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r_github_packages: NOAA-EDAB/ecodata@revert2019
pandoc_version: 2.6
cache: packages

before_install:
- sudo apt-get install libgdal1-dev libproj-dev gdal-bin proj-bin
- sudo apt-get install libgeos-dev
- sudo apt-get install libnetcdf-dev netcdf-bin
- sudo apt-get install libmagick++-dev
- sudo apt-get update
- sudo apt-get install libudunits2-dev

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
