# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
pandoc_version: 2.1.1
cache: packages

before_install:
- sudo apt-get install libgdal1-dev libproj-dev gdal-bin proj-bin
- sudo apt-get install libgeos-dev
- sudo apt-get install libnetcdf-dev netcdf-bin
- sudo apt-get install libmagick++-dev
- Rscript -e "install.packages('ggplot2')"


before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
